EMTrackerDev/Controllers/HomeController.cs
using EMTrackerDev.Data;
using EMTrackerDev.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EMTrackerDev.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly EMTrackerDevContext _context;
        public HomeController(EMTrackerDevContext context, ILogger<HomeController> logger)
        {
            _context = context;
            _logger = logger;
        }

    

        public IActionResult Index(int userId)
        {
            ViewBag.UserId = userId;
            Console.WriteLine("USER5 " + userId);
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(string u, string p)
        {
            var users = _context.Users.ToList();
            for(int i = 0; i< users.Count; i++)
            {
                if (users[i].UserName.Equals(u) && users[i].Password.Equals(p))
                {
                    User logged = users[i];
                    int id = logged.UserId;
                    return RedirectToAction("Index", new {userId=id});

                }

            }

            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EMTrackerDev/Controllers/SamplesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EMTrackerDev.Data;
using EMTrackerDev.Models;
using Microsoft.EntityFrameworkCore.Internal;
using ClosedXML.Excel;
using System.Data;
using System.IO;

namespace EMTrackerDev.Controllers
{
    public class SamplesController : Controller
    {
        private readonly EMTrackerDevContext _context;

        public SamplesController(EMTrackerDevContext context)
        {
            _context = context;
        }

        // GET: Samples
        public async Task<IActionResult> Index(int userId)
        {
            ViewBag.UserId = userId;
            Console.WriteLine("LOOKHERE6 "+userId);
            var eMTrackerDevContext = _context.Samples.Where(s => s.StatusId == 1).Include(s=>s.Analysis).Include(s => s.Test).Include(s => s.ApprovedBy).Include(s => s.CollectedBy).Include(s => s.Status).Include(s=>s.LocationCode);
            return View(await eMTrackerDevContext.ToListAsync());
        }
        public async Task<IActionResult> Collected()
        {
            var eMTrackerDevContext = _context.Samples.Where(s=> s.StatusId == 2).Include(s => s.Analysis).Include(s => s.Test).Include(s => s.ApprovedBy).Include(s => s.CollectedBy).Include(s => s.Status).Include(s => s.LocationCode);
            return View(await eMTrackerDevContext.ToListAsync());
        }
        public async Task<IActionResult> InProcess(int userId)
        {
            ViewBag.UserId = userId;

            var eMTrackerDevContext = _context.Samples.Where(s => s.StatusId == 3).Include(s => s.Analysis).Include(s => s.Test).Include(s => s.ApprovedBy).Include(s => s.CollectedBy).Include(s => s.Status).Include(s => s.LocationCode);
            return View(await eMTrackerDevContext.ToListAsync());
        }
        public async Task<IActionResult> Completed(int userId)
        {
            ViewBag.UserId = userId;

            //  List<TestResult> testResults = _context.TestResults.Where(s => s.EnteredById != null).ToList();
            //  List<int> testIds = testResults.Select(o => o.TestId).ToList();

            //   List<Test> tests = new List<Test>();
            //   for(int i = 0; i < testIds.Count(); i++)
            //   {
            //       tests.Add(_context.Tests.Find(testIds[i]));
            //   }
            //   List<int> Ids = new List<int>();
            //   for(int i=0; i < tests.Count(); i++)
            //   {
            //      Ids.Add((int)tests[i].SampleId);
            //  }
            //  var samples = _context.Samples.Where(c => Ids.Contains(c.SampleID)).Include(s => s.Analysis).Include(s => s.Test).Include(s => s.ApprovedBy).Include(s => s.CollectedBy).Include(s => s.Status);
            var eMTrackerDevContext2 = _context.Samples.Where(s => s.StatusId == 4).Include(s => s.Analysis).Include(s => s.Test).Include(s => s.ApprovedBy).Include(s => s.CollectedBy).Include(s => s.Status).Include(s => s.LocationCode);
            return View(await eMTrackerDevContext2.ToListAsync());
        }
        public async Task<IActionResult> Approved()
        {
            var eMTrackerDevContext = _context.Samples.Where(s => s.StatusId == 5).Include(s => s.Analysis).Include(s => s.Test).Include(s => s.ApprovedBy).Include(s => s.CollectedBy).Include(s => s.Status).Include(s => s.LocationCode);
            return View(await eMTrackerDevContext.ToListAsync());
        }
        public async Task<IActionResult> Rejected()
        {
            var eMTrackerDevContext = _context.Samples.Where(s => s.StatusId == 6).Include(s => s.Analysis).Include(s => s.Test).Include(s => s.ApprovedBy).Include(s => s.CollectedBy).Include(s => s.Status).Include(s => s.LocationCode);
            return View(await eMTrackerDevContext.ToListAsync());
        }
        // GET: Samples/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sample = await _context.Samples
                .Include(s => s.ApprovedBy)
                .Include(s => s.CollectedBy)
                .Include(s => s.Status)
                .FirstOrDefaultAsync(m => m.SampleID == id);
            if (sample == null)
            {
                return NotFound();
            }

            return View(sample);
        }

        // GET: Samples/Create
        public IActionResult Create()
        {
            //ViewData["AnalysisResultId"] = new SelectList(_context.AnalysisResults, "AnalysisResultId", "AnalysisResultId");
         //   ViewData["ApprovedById"] = new SelectList(_context.Users, "UserId", "UserId");
          //  ViewData["CollectedById"] = new SelectList(_context.Users, "UserId", "UserId");
            ViewData["AnalysisId"] = new SelectList(_context.Analyses, "AnalysisId", "Name");
            ViewData["LocationCodeId"] = new SelectList(_context.Locationcodes, "LocationCodeId", "LocationId");

            return View();
        }

        // POST: Samples/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SampleID,AnalysisId,LocationCodeId")] Sample sample)
        {
            if (ModelState.IsValid)
            {
                int analysisId = (int)sample.AnalysisId;
          
                sample.StatusId = 1;
                _context.Add(sample);
                await _context.SaveChangesAsync();
                int sampleId = (int)sample.SampleID;
               // Console.WriteLine("WTFFFF " + sampleId + " " + analysisId);
                var ars = _context.AnalysisResults.Where(s => s.AnalysisId == analysisId).OrderBy(s=> s.AnalysisId);
                List<AnalysisResult> analysisResults = ars.ToList();
                List<Test> tests = new List<Test>();
                for (int i = 0; i < analysisResults.Count(); i++)
                {
                    Console.WriteLine("ARRRR "+analysisResults[i].AnalysisResultId+" ");
                    var test = new Test { AnalysisResultId = analysisResults[i].AnalysisResultId, SampleId = sampleId };
                    tests.Add(test);
                    _context.Add(test);
                }
                await _context.SaveChangesAsync();

                for (int i = 0; i < tests.Count(); i++)
                {
                    Console.WriteLine("TTTTTT " + tests[i].TestID + " ");
                    Console.WriteLine("tttttttttt " + tests[i].AnalysisResultId + " ");

                    var testResult = new TestResult { AnalysisResultId =(int) analysisResults[i].AnalysisResultId, TestId = tests[i].TestID };
                    _context.Add(testResult);
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
          //  ViewData["AnalysisResultId"] = new SelectList(_context.AnalysisResults, "AnalysisResultId", "AnalysisResultId", sample.AnalysisResultId);
          //  ViewData["ApprovedById"] = new SelectList(_context.Users, "UserId", "UserId", sample.ApprovedById);
          //  ViewData["CollectedById"] = new SelectList(_context.Users, "UserId", "UserId", sample.CollectedById);
             ViewData["AnalysisId"] = new SelectList(_context.Analyses, "AnalysisId", "Name", sample.AnalysisId);
            ViewData["LocationCodeId"] = new SelectList(_context.Locationcodes, "LocationCodeId", "LocationId",sample.LocationCodeId);

            //populateAnalysis();
            // populateStatusDropList();
            return View(sample);
        }
    
        // GET: Samples/Tests/5
        public async Task<IActionResult> Tests(int? id, int userId)
        {

            /*   var eMTrackerDevContext = await (from b in _context.Samples
                                  orderby b.SampleID
                                  select b).ToListAsync();
               return View(eMTrackerDevContext.ToList());*/
            /*
               if (id == null)
               {
                   return NotFound();
               }

               var sample = await _context.Tests.Include(test=>test.Sample).Include(test=> test.AnalysisResult)
                   .FirstOrDefaultAsync(m => m.SampleId == id);
               if (sample == null)
               {
                   return NotFound();
               }
               return View(sample);*/
            //test result,  to edit
            var eMTrackerDevContext = _context.Tests.Where(s => s.SampleId == id).Include(s => s.AnalysisResult).Include(s=>s.Sample);
            List<int> Ids = eMTrackerDevContext.Select(o => o.TestID).ToList();
            var testResults = _context.TestResults.Where(c => Ids.Contains(c.TestId)).Include(c=> c.AnalysisResult).Include(c=>c.Test).Include(c=>c.EnteredBy);
            ViewBag.Id = id ;
            ViewBag.UserId = userId;
            return View(await testResults.ToListAsync());

        }


        // GET: Samples/Edit/5                         //add validation
        public async Task<IActionResult> Edit(int? id, int userId)
        {
            Console.WriteLine("EDIT5 " + userId);
            if (id == null)
            {
                return NotFound();
            }

            var sample = await _context.Samples.FindAsync(id);
            sample.CollectedById = userId;
            _context.Update(sample);
            if (sample == null)
            {
                return NotFound();
            }
         //   ViewData["ApprovedById"] = new SelectList(_context.Users, "UserId", "UserId", sample.ApprovedById);
        //    ViewData["CollectedById"] = new SelectList(_context.Users, "UserId", "UserId", sample.CollectedById);

EMTrackerDev/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EMTrackerDevHome</title>
    <script src="https://kit.fontawesome.com/dcfe4a17db.js" crossorigin="anonymous"></script>
    <style>
        .row-cols-sm-4 {
            width: 200px;
            height: 100px;
            text-align: center;
            display: inline-block;
            font-size: 16px;
            border: none;
        }
        .fa-truck {
            width: 100px;
            height: 100px;
        }
        .fa-plus {
            width: 100px;
            height: 100px;
        }
        .fa-vials {
            width: 100px;
            height: 100px;
        }
        .fa-file-alt {
            width: 100px;
            height: 100px;
        }
        .fa-user-check {
            width: 100px;
            height: 100px;
        }
    </style>
</head>
<body>
    <div class="text-center">
        <h1 class="display-4">Welcome *User*</h1>
    </div><br /><br />
    <div class="container">
      <div class="row">
              <div class="col-sm-4">
            </div>
              <div class="text-center">

                  <div class="row-cols-sm-4">
                      <strong>Create</strong>
                      <button id = "create">
                          
                          <!-- solid style -->
                          <i class="fas fa-plus"></i>
                      </button>

                  </div>
                  <div class="row-cols-sm-4">
                      <strong>Collect</strong>
                      <button id = "collect">
                          
                          <!-- solid style -->
                          <i class="fas fa-truck"></i>
                      </button>
                  </div>
                  <div class="row-cols-sm-4">
                      <strong>Analyze</strong>
                      <!-- solid style -->
                      <button id = "analyze">
                          
                          <i class="fas fa-vials"></i>
                      </button>

                  </div>
                  <div class="row-cols-sm-4">
                      <strong>Results</strong>
                      <!-- solid style -->
                      <button id = "results">
                         
                          <i class="fas fa-file-alt"></i>
                      </button>
                  </div>
                  <div class="row-cols-sm-4">
                      <strong>Approve</strong>
                      <!-- solid style -->
                      <button id = "approve">
                         
                          <i class="fas fa-user-check"></i>
                      </button>
                  </div>
              </div>

     <div>
         </div>
         </div>
    </div>
</body>
</html>
<script>
    $("#create").click(function () {
        window.location.href = '@Url.Action("Create", "Samples")';

    });
     $("#collect").click(function () {
         window.location.href = '@Url.Action("Index", "Samples",new{userId=@ViewBag.userID})';


     });
        $("#analyze").click(function () {
        window.location.href = '@Url.Action("Collected", "Samples")';

    });
     $("#results").click(function () {
         window.location.href = '@Url.Action("InProcess", "Samples",new{userId=@ViewBag.userID})';


     });
        $("#approve").click(function () {
        window.location.href = '@Url.Action("Completed", "Samples",new{userId=@ViewBag.userID})';

    });


</script>

EMTrackerDev/Views/Home/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EMTrackerDevLogin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/login.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>


    <style>
        body {
            background-color: lightgrey;
        }
    </style>
</head>

<body class="text-center">
<form id="myForm" action="/Home/Login" method="Post">
        <img class="mb-4" src="~/imgs/srslogo.png" alt="" width="305" height="180">
        <h1 class="h3 mb-3 font-weight-normal" style="color:white;">Please sign in</h1>
        <label for="inputEmpID" class="sr-only">Employee ID</label>
        <input type="text" name="u"id="inputEmpID" class="form-control" placeholder="Employee ID" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" name="p"id="inputPassword" class="form-control" placeholder="Password" required>
        <div class="checkbox mb-3">
            <label style="color:white;">
                <input  type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button id="submitBt" class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    </form>
</body>
</html>
<script>
    $("#submitBt").click(function (e) {
       // e.preventDefault();
       // window.location.href = '@Url.Action("Index", "Home")';
        
    });
</script>